In [3]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [4]:
X = pd.read_csv(r"C:\Users\USER\Desktop\data science\linear_regression_project\raw_data\indian_engineering_student_placement (1).csv")

In [7]:
y = pd.read_csv(r"C:\Users\USER\Desktop\data science\linear_regression_project\raw_data\placement_targets.csv")

In [8]:
X.head()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,aptitude_skill_rating,hackathons_participated,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,5,4,5,6.5,8,Yes,Medium,Tier 2,Yes,Medium
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,3,4,1,7.1,8,Yes,Medium,Tier 3,Yes,Low
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,4,6,3,6.1,2,No,Low,Tier 2,Yes,High
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,4,2,2,7.3,7,No,Medium,Tier 1,Yes,Low
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,3,2,1,6.0,7,No,Medium,Tier 1,Yes,Medium

In [9]:
y.head()

   Student_ID placement_status  salary_lpa
0           1           Placed       14.95
1           2           Placed       14.91
2           3           Placed       17.73
3           4           Placed       14.52
4           5           Placed       15.91

In [10]:
X.drop(['Student_ID'], axis = 1)
y.drop(['Student_ID', 'placement_status'],axis = 1)

      salary_lpa
0          14.95
1          14.91
2          17.73
3          14.52
4          15.91
...          ...
4995       19.35
4996        0.00
4997       19.13
4998       16.53
4999       20.00

[5000 rows x 1 columns]