In [12]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [13]:
X = pd.read_csv(r"C:\Users\USER\Desktop\data science\linear_regression_project\raw_data\indian_engineering_student_placement (1).csv")

In [14]:
y = pd.read_csv(r"C:\Users\USER\Desktop\data science\linear_regression_project\raw_data\placement_targets.csv")

In [15]:
X.head()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,aptitude_skill_rating,hackathons_participated,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,5,4,5,6.5,8,Yes,Medium,Tier 2,Yes,Medium
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,3,4,1,7.1,8,Yes,Medium,Tier 3,Yes,Low
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,4,6,3,6.1,2,No,Low,Tier 2,Yes,High
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,4,2,2,7.3,7,No,Medium,Tier 1,Yes,Low
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,3,2,1,6.0,7,No,Medium,Tier 1,Yes,Medium

In [16]:
y.head()

   Student_ID placement_status  salary_lpa
0           1           Placed       14.95
1           2           Placed       14.91
2           3           Placed       17.73
3           4           Placed       14.52
4           5           Placed       15.91

In [17]:
X=X.drop(['Student_ID','extracurricular_involvement'], axis = 1)
y=y.drop(['Student_ID', 'placement_status'],axis = 1)

In [18]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   gender                      5000 non-null   object
 1   branch                      5000 non-null   object
 2   cgpa                        5000 non-null   float64
 3   tenth_percentage            5000 non-null   float64
 4   twelfth_percentage          5000 non-null   float64
 5   backlogs                    5000 non-null   int64
 6   study_hours_per_day         5000 non-null   float64
 7   attendance_percentage       5000 non-null   float64
 8   projects_completed          5000 non-null   int64
 9   internships_completed       5000 non-null   int64
 10  coding_skill_rating         5000 non-null   int64
 11  communication_skill_rating  5000 non-null   int64
 12  aptitude_skill_rating       5000 non-null   int64
 13  hackathons_participated     5000 non-null   int64
 14  certifications_count        5000 non-null   int64
 15  sleep_hours                 5000 non-null   float64
 16  stress_level                5000 non-null   int64
 17  part_time_job               5000 non-null   object
 18  family_income_level         5000 non-null   object
 19  city_tier                   5000 non-null   object
 20  internet_access             5000 non-null   object
dtypes: float64(6), int64(9), object(6)
memory usage: 820.4+ KB

train  test and split

In [19]:
train_test_split(X, y, test_size=0.2)

[      gender branch   cgpa  tenth_percentage  twelfth_percentage  backlogs  \
 15      Male    CSE   8.57              79.5                79.0         1
 171     Male     ME   9.17              84.6                87.3         0
 3880    Male     ME   9.36              90.0                81.9         0
 4848  Female     ME   8.53              78.5                78.0         0
 1120  Female    CSE   8.74              91.1                77.0         0
 ...      ...    ...    ...               ...                 ...       ...
 891   Female     ME  10.00              85.9                93.6         0
 2296    Male    CSE   8.57              68.8                71.5         2
 2387  Female     IT   8.39              75.8                75.3         2
 3826    Male     ME  10.00              89.9                83.5         0
 1819    Male     CE   8.11              68.4                79.0         1

       study_hours_per_day  attendance_percentage  projects_completed  \
 15                    6.5                   74.2                   7
 171                   7.0                   84.4                   4
 3880                  8.9                   83.6                   6
 4848                  6.7                   85.4                   7
 1120                  4.9                   82.4                   5
 ...                   ...                    ...                 ...
 891                   6.3                   86.7                   7
 2296                  0.6                   54.9                   8
 2387                  1.6                   68.2                   6
 3826                  7.2                   85.9                   8
 1819                  3.7                   66.9                   7

       internships_completed  ...  communication_skill_rating  \
 15                        3  ...                           4
 171                       3  ...                           1
 3880                      1  ...                           3
 4848                      3  ...                           2
 1120                      3  ...                           5
 ...                     ...  ...                         ...
 891                       4  ...                           4
 2296                      1  ...                           3
 2387                      4  ...                           2
 3826                      3  ...                           2
 1819                      2  ...                           4

       aptitude_skill_rating  hackathons_participated  certifications_count  \
 15                        4                        6                     3
 171                       5                        1                     4
 3880                      5                        4                     5
 4848                      5                        5                     4
 1120                      4                        3                     3
 ...                     ...                      ...                   ...
 891                       4                        5                     1
 2296                      4                        5                     1
 2387                      5                        5                     3
 3826                      5                        4                     2
 1819                      4                        6                     3

       sleep_hours  stress_level  part_time_job family_income_level city_tier  \
 15            6.5             3             No                 Low    Tier 3
 171           5.3            10             No                 Low    Tier 1
 3880          7.1             9             No              Medium    Tier 1
 4848          6.0             7            Yes              Medium    Tier 1
 1120          6.8             5             No              Medium    Tier 3
 ...           ...           ...            ...                 ...       ...
 891           4.0             6             No                 Low    Tier 2
 2296          8.7             6             No              Medium    Tier 3
 2387          5.6             7             No              Medium    Tier 2
 3826          6.4             2             No              Medium    Tier 3
 1819          8.3            10             No              Medium    Tier 3

      internet_access
 15               Yes
 171              Yes
 3880             Yes
 4848             Yes
 1120             Yes
 ...              ...
 891              Yes
 2296             Yes
 2387             Yes
 3826             Yes
 1819              No

 [4000 rows x 21 columns],
       gender branch  cgpa  tenth_percentage  twelfth_percentage  backlogs  \
 2486    Male    ECE  9.13              77.4                82.3         1
 2914    Male    CSE  8.58              77.4                73.6         0
 2223    Male    ECE  9.45              86.5                83.7         0
 1277  Female    ECE  6.64              55.5                58.6         0
 2280    Male     ME  7.75              72.7                65.7         1
 ...      ...    ...   ...               ...                 ...       ...
 2246    Male     ME  8.88              79.1                76.8         0
 4018    Male    CSE  8.55              75.3                78.3         1
 129     Male     IT  7.38              70.5                68.2         0
 297     Male     ME  7.55              75.5                72.9         1
 976     Male    CSE  9.44              77.2                81.4         0

       study_hours_per_day  attendance_percentage  projects_completed  \
 2486                  5.3                   81.5                   8
 2914                  6.9                   73.2                   7
 2223                  2.5                   69.4                   8
 1277                  0.6                   63.3                   7
 2280                  3.0                   77.7                   5
 ...                   ...                    ...                 ...
 2246                  2.7                   70.5                   8
 4018                  2.8                   78.3                   8
 129                   1.3                   72.0                   3
 297                   4.7                   82.8                   3
 976                   3.7                   80.0                   7

       internships_completed  ...  communication_skill_rating  \
 2486                      2  ...                           3
 2914                      2  ...                           4
 2223                      2  ...                           2
 1277                      1  ...                           4
 2280                      3  ...                           1
 ...                     ...  ...                         ...
 2246                      1  ...                           5
 4018                      2  ...                           3
 129                       1  ...                           5
 297                       2  ...                           1
 976                       4  ...                           4

       aptitude_skill_rating  hackathons_participated  certifications_count  \
 2486                      5                        4                     5
 2914                      5                        4                     5
 2223                      5                        5                     4
 1277                      3                        4                     3
 2280                      4                        3                     1
 ...                     ...                      ...                   ...
 2246                      5                        5                     3
 4018                      4                        5                     2
 129                       4                        1                     4
 297                       4                        3                     5
 976                       5                        6                     4

       sleep_hours  stress_level  part_time_job family_income_level city_tier  \
 2486          7.9             7             No              Medium    Tier 2
 2914          7.5             5             No                High    Tier 1
 2223          7.0             9            Yes              Medium    Tier 2
 1277          7.0             4             No              Medium    Tier 2
 2280          6.7            10             No              Medium    Tier 2
 ...           ...           ...            ...                 ...       ...
 2246          5.1             4             No                 Low    Tier 1
 4018          6.0             4             No                High    Tier 2
 129           9.0             7            Yes              Medium    Tier 2
 297           7.7             9             No              Medium    Tier 1
 976           8.4             9             No                High    Tier 2

      internet_access
 2486              No
 2914             Yes
 2223             Yes
 1277             Yes
 2280             Yes
 ...              ...
 2246             Yes
 4018             Yes
 129              Yes
 297              Yes
 976              Yes

 [1000 rows x 21 columns],
       salary_lpa
 15         20.00
 171        15.98
 3880       12.19
 4848       17.70
 1120       19.08
 ...          ...
 891        17.80
 2296       17.74
 2387       19.96
 3826       17.86
 1819       17.70

 [4000 rows x 1 columns],
       salary_lpa
 2486       15.30
 2914       19.14
 2223       18.36
 1277       10.17
 2280        0.00
 ...          ...
 2246       18.37
 4018       20.00
 129        11.65
 297         0.00
 976        20.00

 [1000 rows x 1 columns]]

In [20]:
X.train.shape

AttributeError: 'DataFrame' object has no attribute 'train'

In [21]:
numerical_data = X.select_dtypes(include=['int', 'float']).columns
categorical_data = X.select_dtypes(exclude=['int', 'float']).columns

In [22]:
numerical_data

Index(['cgpa', 'tenth_percentage', 'twelfth_percentage', 'backlogs',
       'study_hours_per_day', 'attendance_percentage', 'projects_completed',
       'internships_completed', 'coding_skill_rating',
       'communication_skill_rating', 'aptitude_skill_rating',
       'hackathons_participated', 'certifications_count', 'sleep_hours',
       'stress_level'],
      dtype='object')

In [23]:
categorical_data 

nominal_data = ['gender','branch','part_time_job',]
ordinal_data = ['family_income_level', 'city_tier',]

In [24]:
# scaling >> converting the data into a same scale
# normalization standardization
# min max, z score

In [25]:
from sklearn.preprocessing import StandardScaler, minmax_scale

In [27]:
Min_max_Scaler = MinMaxScaler()

NameError: name 'MinMaxScaler' is not defined

In [29]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [1]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder