In [1]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
X = pd.read_csv(r"C:\Users\USER\Desktop\data science\linear_regression_project\raw_data\indian_engineering_student_placement (1).csv")

In [3]:
y = pd.read_csv(r"C:\Users\USER\Desktop\data science\linear_regression_project\raw_data\placement_targets.csv")

In [4]:
X.head()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,aptitude_skill_rating,hackathons_participated,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,5,4,5,6.5,8,Yes,Medium,Tier 2,Yes,Medium
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,3,4,1,7.1,8,Yes,Medium,Tier 3,Yes,Low
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,4,6,3,6.1,2,No,Low,Tier 2,Yes,High
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,4,2,2,7.3,7,No,Medium,Tier 1,Yes,Low
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,3,2,1,6.0,7,No,Medium,Tier 1,Yes,Medium

In [5]:
y.head()

   Student_ID placement_status  salary_lpa
0           1           Placed       14.95
1           2           Placed       14.91
2           3           Placed       17.73
3           4           Placed       14.52
4           5           Placed       15.91

In [6]:
X=X.drop(['Student_ID','extracurricular_involvement'], axis = 1)
y=y.drop(['Student_ID', 'placement_status'],axis = 1)

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   gender                      5000 non-null   object
 1   branch                      5000 non-null   object
 2   cgpa                        5000 non-null   float64
 3   tenth_percentage            5000 non-null   float64
 4   twelfth_percentage          5000 non-null   float64
 5   backlogs                    5000 non-null   int64
 6   study_hours_per_day         5000 non-null   float64
 7   attendance_percentage       5000 non-null   float64
 8   projects_completed          5000 non-null   int64
 9   internships_completed       5000 non-null   int64
 10  coding_skill_rating         5000 non-null   int64
 11  communication_skill_rating  5000 non-null   int64
 12  aptitude_skill_rating       5000 non-null   int64
 13  hackathons_participated     5000 non-null   int64
 14  certifications_count        5000 non-null   int64
 15  sleep_hours                 5000 non-null   float64
 16  stress_level                5000 non-null   int64
 17  part_time_job               5000 non-null   object
 18  family_income_level         5000 non-null   object
 19  city_tier                   5000 non-null   object
 20  internet_access             5000 non-null   object
dtypes: float64(6), int64(9), object(6)
memory usage: 820.4+ KB

train  test and split

In [8]:
train_test_split(X, y, test_size=0.2)

[      gender branch   cgpa  tenth_percentage  twelfth_percentage  backlogs  \
 3913  Female    CSE  10.00              95.1                86.5         0
 1512  Female     IT   8.05              77.7                75.1         0
 4260    Male    ECE   9.79              81.0                82.6         0
 3834    Male     IT   8.67              80.2                84.9         1
 703     Male    CSE   9.01              80.9                76.7         1
 ...      ...    ...    ...               ...                 ...       ...
 1450    Male     IT   8.45              81.7                75.3         0
 2504    Male     ME   7.39              61.3                74.9         0
 3323    Male    ECE   6.47              50.0                52.0         1
 1920  Female     IT   8.92              81.4                76.3         0
 1382  Female    CSE  10.00              90.5                95.8         0

       study_hours_per_day  attendance_percentage  projects_completed  \
 3913                  1.5                   59.2                   6
 1512                  7.1                   77.0                   5
 4260                  4.5                   71.3                   7
 3834                  6.1                   75.7                   8
 703                   2.5                   60.5                   7
 ...                   ...                    ...                 ...
 1450                  2.5                   66.3                   5
 2504                  5.8                   69.6                   7
 3323                  5.4                   73.8                   3
 1920                  2.8                   66.7                   8
 1382                  2.4                   66.1                   7

       internships_completed  ...  communication_skill_rating  \
 3913                      2  ...                           1
 1512                      2  ...                           2
 4260                      4  ...                           5
 3834                      4  ...                           5
 703                       4  ...                           3
 ...                     ...  ...                         ...
 1450                      4  ...                           3
 2504                      1  ...                           3
 3323                      0  ...                           4
 1920                      3  ...                           1
 1382                      4  ...                           2

       aptitude_skill_rating  hackathons_participated  certifications_count  \
 3913                      5                        5                     3
 1512                      5                        1                     2
 4260                      5                        5                     1
 3834                      4                        5                     9
 703                       4                        4                     4
 ...                     ...                      ...                   ...
 1450                      3                        3                     1
 2504                      4                        6                     2
 3323                      3                        3                     1
 1920                      5                        4                     4
 1382                      5                        5                     6

       sleep_hours  stress_level  part_time_job family_income_level city_tier  \
 3913          6.0             1             No                High    Tier 2
 1512          8.0            10             No                High    Tier 2
 4260          7.7             6             No              Medium    Tier 2
 3834          6.3             5             No              Medium    Tier 2
 703           7.0             1             No                High    Tier 1
 ...           ...           ...            ...                 ...       ...
 1450          5.4             3             No                 Low    Tier 3
 2504          8.3             2            Yes              Medium    Tier 2
 3323          8.6            10            Yes              Medium    Tier 1
 1920          6.7            10             No                High    Tier 2
 1382          9.0             2             No              Medium    Tier 2

      internet_access
 3913             Yes
 1512             Yes
 4260             Yes
 3834             Yes
 703               No
 ...              ...
 1450             Yes
 2504             Yes
 3323             Yes
 1920             Yes
 1382             Yes

 [4000 rows x 21 columns],
       gender branch  cgpa  tenth_percentage  twelfth_percentage  backlogs  \
 2515  Female     IT  8.56              76.8                78.2         0
 783     Male    CSE  8.32              72.3                78.7         0
 4790    Male    CSE  7.52              60.2                74.9         0
 3758    Male    CSE  9.34              80.0                89.4         0
 2794    Male     CE  9.50              86.2                74.6         1
 ...      ...    ...   ...               ...                 ...       ...
 2769  Female     CE  6.37              51.2                54.9         0
 3827    Male    ECE  8.89              81.8                77.1         1
 278   Female     IT  8.26              70.3                70.8         1
 4373    Male     IT  8.78              72.1                80.8         0
 3267    Male    ECE  7.84              71.5                64.3         0

       study_hours_per_day  attendance_percentage  projects_completed  \
 2515                  6.8                   83.2                   7
 783                   2.2                   68.5                   3
 4790                  4.8                   78.0                   8
 3758                  3.7                   69.8                   6
 2794                  2.6                   68.0                   3
 ...                   ...                    ...                 ...
 2769                  5.7                   84.5                   3
 3827                  4.6                   74.7                   4
 278                   4.1                   74.8                   5
 4373                  5.3                   78.3                   8
 3267                  4.7                   73.3                   1

       internships_completed  ...  communication_skill_rating  \
 2515                      2  ...                           5
 783                       3  ...                           5
 4790                      1  ...                           1
 3758                      3  ...                           5
 2794                      4  ...                           1
 ...                     ...  ...                         ...
 2769                      1  ...                           5
 3827                      3  ...                           5
 278                       3  ...                           5
 4373                      4  ...                           3
 3267                      2  ...                           2

       aptitude_skill_rating  hackathons_participated  certifications_count  \
 2515                      4                        5                     1
 783                       4                        0                     6
 4790                      4                        6                     4
 3758                      4                        4                     2
 2794                      5                        3                     3
 ...                     ...                      ...                   ...
 2769                      4                        3                     0
 3827                      4                        5                     3
 278                       4                        3                     2
 4373                      4                        5                     6
 3267                      4                        3                     1

       sleep_hours  stress_level  part_time_job family_income_level city_tier  \
 2515          6.5             7             No              Medium    Tier 3
 783           6.4             5             No              Medium    Tier 2
 4790          5.9            10             No              Medium    Tier 1
 3758          7.7             7             No                 Low    Tier 2
 2794          7.9             7             No              Medium    Tier 3
 ...           ...           ...            ...                 ...       ...
 2769          7.1             6            Yes              Medium    Tier 3
 3827          6.6             6             No                 Low    Tier 3
 278           8.5            10             No              Medium    Tier 2
 4373          5.6             6            Yes              Medium    Tier 3
 3267          8.5             8             No              Medium    Tier 2

      internet_access
 2515             Yes
 783              Yes
 4790             Yes
 3758             Yes
 2794             Yes
 ...              ...
 2769             Yes
 3827             Yes
 278              Yes
 4373             Yes
 3267             Yes

 [1000 rows x 21 columns],
       salary_lpa
 3913       17.11
 1512       15.14
 4260       19.88
 3834       18.94
 703        18.72
 ...          ...
 1450       17.23
 2504       15.60
 3323        0.00
 1920       20.00
 1382       18.87

 [4000 rows x 1 columns],
       salary_lpa
 2515       16.69
 783        19.51
 4790       18.09
 3758       20.00
 2794       15.80
 ...          ...
 2769        0.00
 3827       18.91
 278        18.34
 4373       20.00
 3267       13.41

 [1000 rows x 1 columns]]

In [ ]:
X.train.shape

In [18]:
numerical_data = X.select_dtypes(include=['int', 'float']).columns
categorical_data = X.select_dtypes(exclude=['int', 'float']).columns

In [19]:
numerical_data

Index(['cgpa', 'tenth_percentage', 'twelfth_percentage', 'backlogs',
       'study_hours_per_day', 'attendance_percentage', 'projects_completed',
       'internships_completed', 'coding_skill_rating',
       'communication_skill_rating', 'aptitude_skill_rating',
       'hackathons_participated', 'certifications_count', 'sleep_hours',
       'stress_level'],
      dtype='object')

In [ ]:
categorical_data 

nominal_data = ['gender','branch','part_time_job',]
ordinal_data = ['family_income_level', 'city_tier',]

Index(['gender', 'branch', 'part_time_job', 'family_income_level', 'city_tier',
       'internet_access'],
      dtype='object')

In [ ]:
# scaling >> converting the data into a same scale
# normalization standardization
# min max, z score